import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/theme";
import ReduxProvider from "@/components/ReduxProvider/ReduxProvider";
import {Toaster} from "react-hot-toast"
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Social App",
  description: "Generated by create next app",
  icons:{
    icon:"/favicon.ico"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable}  ${geistSans.variable} antialiased bg-gray-100 select-none`}
      >
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <ReduxProvider>
            {children}
            <Toaster containerStyle={{textAlign:"center",fontFamily:"sans-serif"}}/>
            </ReduxProvider>
          
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
